### ISSUE TITLE
Can not build Android on RN 0.73.9

### ISSUE THREAD

**Issue by Alexxzz** [idenfy/ReactNativeSDK#12]
Hello,

Steps to reproduce:
```
npx react-native@0.73.9 init NewRNProj --version 0.73.9
cd NewRNProj
yarn add @idenfy/react-native-sdk
yarn android
```

Error:
```
BUILD FAILED in 1s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * Where:
Settings file '.../NewRNProj/android/settings.gradle' line: 2 * What went wrong:
A problem occurred evaluating settings 'NewRNProj'.
> Could not read script '.../NewRNProj/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.
```

My guess is this is because the library has dependency on RN 0.73.6

**Comment by viktasidenfy** [comment]
Hey, it seems that the project is working fine with RN 0.73.9. We've tried running a new project and installing the package using `npm`. And the project builds successfully.

```
npx react-native@0.73.9 init NewRNProj --version 0.73.9
cd NewRNProj
npm install @idenfy/react-native-sdk
npx react-native run-android
```

**Comment by Alexxzz** [comment]
And if you try with `yarn` ?
We use version `1.22.19`

**Comment by viktasidenfy** [comment]
Yes, we can replicate this issue using `yarn`. We will release a new version of the SDK by the end of the week and with this release, we will try to support `yarn` as well. For the time being, as a workaround, you can try to installing the package using npm.

**Comment by Alexxzz** [comment]
Great! Thank you

**Comment by viktasidenfy** [comment]
@Alexxzz It seems the problem was in the React Native version, so we've updated it to `0.73.9` and now the `yarn android` does work.

**Comment by Alexxzz** [comment]
It works, thank you!
