### ISSUE TITLE
How to use "Document Recognition" with RN SDK?

### ISSUE THREAD

**Issue by Alexxzz** [idenfy/ReactNativeSDK#14]
Hello, 

Is it possible with RN SDK? 

In iOS [documentation](https://documentation.idenfy.com/mobile/iOS/ios-sdk#1-adding-the-document-recognition-dependency) it suggests to add pod to Podfile
```
pod 'iDenfySDK/iDenfyRecognition', '8.5.7'
```
which is probably not what you do when using RN plugin.

**Comment by viktasidenfy** [comment]
Yes, if you wish to use this feature, you must fork this repository and change the` idenfy-react-native.podspec` file to include iDenfyRecognition  `s.dependency "iDenfySDK-Static/iDenfyRecognition-Static", "8.5.7"`. 
Using the plugin from `npmjs` is not possible.
