### ISSUE TITLE
Frameworks with conflicting names: facetecsdk.xcframework [react-native/Expo]

### ISSUE THREAD

**Issue by esipavicius** [idenfy/ReactNativeSDK#15]
### iOS

I have installed [Ondato](https://github.com/ondato/ondato-sdk-react-native) and this library using also facetecsdk.
Also we have Idenfy. 
We have configuration between Idenfy or Ondato and we need Integrate both in app.

<img width="927" alt="Screenshot 2024-11-08 at 17 29 37" src="https://github.com/user-attachments/assets/2af0df85-6221-4981-9b0d-8804173a3848">

Im not good at iOS development, so I need some information what we can do? 

### Android

<img width="1592" alt="Screenshot 2024-11-08 at 18 01 22" src="https://github.com/user-attachments/assets/778bd0fa-a0fa-4c47-952f-70c280a80d68">

**Comment by viktasidenfy** [comment]
To avoid this conflict you can use our iDenfySDK version without 3D liveness check. For this, you would have to fork our repository (https://github.com/idenfy/ReactNativeSDK) and edit the idenfy-react-native.podspec file. Just change the 
`s.dependency "iDenfySDK-Static/iDenfyLiveness-Static", "8.5.7"` to `s.dependency "iDenfySDK-Static", "8.5.7"` and use the forked package in your project. 

For Android you are missing a repository, double check your repositories for all projects:

```
allprojects {
  repositories {
    maven { url 'https://jitpack.io' }
    maven { url 'https://developer.huawei.com/repo/' }
  }
}
```

**Comment by viktasidenfy** [comment]
Check your **podfile** in ios folder, if the minimum version is set:

`platform :ios, '13.4'`

**Comment by viktasidenfy** [comment]
Make sure you have read the setup documentation and double checked the integration. Otherwise similar issues might occur.

**Comment by esipavicius** [comment]
@viktasidenfy Ok I will try. For Expo its not easy part edit **Podfile**. I will create plugin to edit **Podfile** and other stuff. 
I'll tell you when I'm done.

Thanx!

**Comment by esipavicius** [comment]
@viktasidenfy Edited Podfile and got `Lottie` not found. What I missing?
<img width="1595" alt="Screenshot 2024-11-12 at 16 20 11" src="https://github.com/user-attachments/assets/7986ff99-e409-462f-be4e-e582738f08be">

**Comment by viktasidenfy** [comment]
Could you show your podfile?

**Comment by esipavicius** [comment]
> Could you show your podfile?

```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

use_autolinking_method_symbol = ('use' + '_native' + '_modules!').to_sym
origin_autolinking_method = self.method(use_autolinking_method_symbol)
self.define_singleton_method(use_autolinking_method_symbol) do |*args|
  if ENV['EXPO_UNSTABLE_CORE_AUTOLINKING'] == '1'
    Pod::UI.puts('Using expo-modules-autolinking as core autolinking source'.green)
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
    origin_autolinking_method.call(config_command)
  else
    origin_autolinking_method.call()
  end
end

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'Verifo' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|

      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end

        if target.name == "lottie-ios"
          target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = '13.0'
          end
        end
      end
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

```

**Comment by esipavicius** [comment]
Hmmm... I think Im almost done but now this.

<img width="1586" alt="Screenshot 2024-11-12 at 16 54 16" src="https://github.com/user-attachments/assets/db6b97fe-be98-41bb-b0c3-bf35c62e27b6">
<img width="1593" alt="Screenshot 2024-11-12 at 16 54 25" src="https://github.com/user-attachments/assets/bb40f771-1c2e-4b78-b834-a15d0428d91b">

**Comment by viktasidenfy** [comment]
Update xCode to version 16.0

**Comment by esipavicius** [comment]
Ok I will try. Now I need update MAC and update xCode

**Comment by esipavicius** [comment]
@viktasidenfy After MAC and xCode update app builded successfully for **iOS**. Little bit later I will check Android.

**Comment by esipavicius** [comment]
@viktasidenfy One more question. Maybe you can know why is this happening. When using iDenfy SDK my app freezes on boot/SplashScreen.
```
import { start, startFaceReAuth } from '@idenfy/react-native-sdk';
start(...);
```

If I comment out start or startFaceReAuth. Refresh app render. uncomment when it works.
<img width="390" alt="Screenshot 2024-11-14 at 18 46 57" src="https://github.com/user-attachments/assets/3e7e4807-00f5-4987-8b52-f73200268ca9">
<img width="435" alt="Screenshot 2024-11-14 at 18 47 23" src="https://github.com/user-attachments/assets/12c16c93-0a5a-4782-85d3-c8a0bdc54421">
<img width="377" alt="Screenshot 2024-11-14 at 18 47 37" src="https://github.com/user-attachments/assets/67825122-9881-4002-8944-d4ad68a7d1eb">

**Comment by esipavicius** [comment]
> It's because of the simulator, it will work fine on a real device.

Ok, I will check.

**Comment by esipavicius** [comment]
@viktasidenfy I fixed it by getting `NativeModules` calling `start` or other method. I think its need some lazy loading if setting it globally. 

Edited code `index.tsx`
```
import { NativeModules, Platform } from 'react-native';

const getIdenfyReactNativeModule = () => {
    const LINKING_ERROR =
        `The package 'idenfy-react-native' doesn't seem to be linked. Make sure: \n\n` +
        Platform.select({ ios: "- You have run 'pod install'\n", default: '' }) +
        '- You rebuilt the app after installing the package\n' +
        '- You are not using Expo Go\n';

    return NativeModules.IdenfyReactNative
        ? NativeModules.IdenfyReactNative
        : new Proxy(
            {},
            {
                get() {
                    throw new Error(LINKING_ERROR);
                },
            }
        );
}

export function start(config: any): Promise<any> {
  return getIdenfyReactNativeModule().start(config);
}

export function startFaceReAuth(config: any): Promise<any> {
  return getIdenfyReactNativeModule().startFaceReAuth(config);
}
```

**Comment by viktasidenfy** [comment]
You can pass` checkLiveness: false` in the request body along with the token generation

**Comment by esipavicius** [comment]
> You can pass` checkLiveness: false` in the request body along with the token generation

If like this its not working.
<img width="498" alt="Screenshot 2024-11-19 at 10 33 42" src="https://github.com/user-attachments/assets/086bda61-7a36-4223-9627-d570c00bd8bc">
